### ISSUE TITLE
Workflow list view

### ISSUE THREAD

**Issue by ABN-Askham** [placeposition/alpaka-user-group#1]
Please can the workflow default view be for any items relating to forthcoming dates. 

Please can we also remove or approve all items requiring approval where the events have already happened.

**Comment by placeposition** [comment]
<img width="1627" alt="Screenshot 2020-02-05 at 21 08 00" src="https://user-images.githubusercontent.com/4497319/73883301-9bb86c00-485b-11ea-845a-90780bb1f8f7.png">

The filter has an Actions item on the second row now- with this you can set a status for everything in your list view and so make short work of getting rid of older or expired workflow instances.
