### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by ABN-Askham** [placeposition/alpaka-user-group#13]
Is there an option (not mission critical) to set events to be recurring? E.g. staff meetings, trainings, services etc.

**Comment by placeposition** [comment]
clone and repeat individual events is now on the Activity List page - I want to clone and repeat a week or a month - on its way!

**Comment by placeposition** [comment]
Recurring a whole week now in production

<img width="210" alt="Screenshot 2020-10-19 at 22 10 09" src="https://user-images.githubusercontent.com/4497319/96512065-e0542e00-1257-11eb-954f-9d69e7d3dd7b.png">


<img width="598" alt="Screenshot 2020-10-19 at 22 10 01" src="https://user-images.githubusercontent.com/4497319/96512175-011c8380-1258-11eb-8fc6-efd6f6f22d65.png">
