### ISSUE TITLE
Reset password link issue

### ISSUE THREAD

**Issue by BetterFoodHR** [placeposition/alpaka-user-group#21]
Lots of team members having issues with the reset password function - button just doesn't go anywhere

**Comment by placeposition** [comment]
I found a reset behaviour that failed when the user was new. We only export user details to the identity provider when they first log in, so if someone tries to reset their password without ever having logged in its a path that fails. I have it covered now so will test this scenario and close this issue. All emails tested and working, reset token validity extended to 24 hours

**Comment by placeposition** [comment]
Fixed
