### ISSUE TITLE
Clone rota error

### ISSUE THREAD

**Issue by BetterFoodHR** [placeposition/alpaka-user-group#25]
Clone rota with shifts and Clone rota with start date do the same thing?
![image](https://user-images.githubusercontent.com/72070455/94568172-165b4f00-0264-11eb-9094-d42b088ee5a8.png)
![image](https://user-images.githubusercontent.com/72070455/94568196-1d825d00-0264-11eb-8dd6-c26a6aa63e09.png)

**Comment by BetterFoodHR** [comment]
just says 'coming soon' when you try to click yes on the clone rota with start date

**Comment by placeposition** [comment]
whole clone thing revised.
