### ISSUE TITLE
Total presence time being out by one second

### ISSUE THREAD

**Issue by KateRodgers** [placeposition/alpaka-user-group#33]
DR request - Often the total presence reading is one second out. This can not be manually overwritten as the seconds are not visible. Can this be changed? - PR not include the seconds in the presence reading.

**Comment by placeposition** [comment]
This is recording presence readings- round to nearest minute always

**Comment by placeposition** [comment]
New readings round to the nearest minute inbound from the Presence app. 
Old readings will also round if edited.
