### ISSUE TITLE
T for Training

### ISSUE THREAD

**Issue by ABN-Askham** [placeposition/alpaka-user-group#4]
In the training list view there are some items which are 'T' - these must have been entered by a user at our end but I need your help to figure out where these are coming from and stop them from being entered (or figure out why they are needed and work out the best way of doing whatever the user is trying to do)

**Comment by placeposition** [comment]
All the events named "T" in your schedule are from the Rota feature, rota #62, #67, and #113. I looked at the default shift patterns and there isn't a shift called "T" so it must have been added manually to each rota shift list and not saved in the list of shift patterns.

Once you are logged in to Alpaka visit any rota and look at the url in the browser  - 

**alpaka.io/rotas/95** (for example)

You can change the number at the end to the ID's above and press return to jump straight to them.
