### ISSUE TITLE
Shift creation by managers not possible.

### ISSUE THREAD

**Issue by KateRodgers** [placeposition/alpaka-user-group#44]
Managers request -  No flexibility to add a shift of my choice- have to email Daisy to add it.

**Comment by placeposition** [comment]
In previous Alpaka clients where the shift creation was available on the rota page itself, we saw a proliferation of identical and unnecessary shifts with no centralised oversight. The extensive list of nonsense then makes it hard for managers to create rotas with so many shifts in the palette to select from.

Limiting shift control wasn't done to inconvenience managers- it was done to make shifts and working patterns more reliable and predictable for the team and for the administers who may need to digest and correct working times from the clocking in and out readings- if just about anything passes as a shift there is no clear-cut method for them to work efficiently and sensibly.

I am available on support to make new shift patterns on demand, but I will also need to check with Daisy whether the shift is valid and useful to her in admin.
