### ISSUE TITLE
Contacts - pink and not visible

### ISSUE THREAD

**Issue by ABN-Askham** [placeposition/alpaka-user-group#5]
When I look at contact view, all the bars have been turned pink, and for some reason there are entries which are called 'no contact' 
- i can't seem to set the bars at the top to show me all the residents/ relatives - there used to be over 150 entries and now there are 58?
- can we please look into where these have come from so I can go back to the relevant user?

**Comment by placeposition** [comment]
I suspect your filter was set to look at inactive contacts- reddish pink is used in all list views to indicate inactive rows.

I checked the filter and got a large number of results when filtering for active only.

<img width="1268" alt="Screenshot 2020-02-05 at 19 33 35" src="https://user-images.githubusercontent.com/4497319/73876162-6ce7c900-484e-11ea-9612-a63a68b9d9fb.png">
