### ISSUE TITLE
presence readings not pairing 

### ISSUE THREAD

**Issue by KateRodgers** [placeposition/alpaka-user-group#50]
Management request - Some presence readings not pairing – example Millie Williams

**Comment by placeposition** [comment]
The V2 editor is now more robust - correcting a reading or adding a missing pair is very fast and very simple. However- the rules regarding pair detection might have some strange cases where a pair is left stranded- it assumes a maximum length of shift is 18 hours for example and so will not pair with even a stranded result that is too far away.
