### ISSUE TITLE
Manager override button for conflicts 

### ISSUE THREAD

**Issue by KateRodgers** [placeposition/alpaka-user-group#53]
Management request - Can we have a manager override button for conflicts – so it alerts you to the conflict but you have the ability to override it

**Comment by placeposition** [comment]
Conflicts are deliberate and need to stay in the way of an attempt to double book someone or something. 

If the intention is to replace what is in the way the warning and preventing mechanism is there for someone to remove the conflicting item so you can proceed with the new event creation - overriding a feature designed to prevent mistake and create accountability is not the solution.
